version: '2'
services:
    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /applications/nzbget:/config
            - /downloads:/downloads
        restart: always
        environment:
            - TZ=America/New_York
        ports:
            - '6789:6789'
    sonarr:
        image: linuxserver/sonarr:latest
        container_name: sonarr
        depends_on:
            - nzbget
        volumes:
            - /applications/sonarr:/config
            - /downloads:/downloads
            - /media/tv:/tv
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=1000
        ports:
            - 8989:8989/tcp
    radarr:
        image: linuxserver/radarr:latest
        container_name: radarr
        depends_on:
            - nzbget
        volumes:
            - /applications/radarr:/config
            - /downloads:/downloads
            - /media/movies:/movies
        environment:
            - TZ=America/New_York
        ports:
            - 7878:7878/tcp
    tatulli:
        image: linuxserver/tautulli
        container_name: plexreports
        volumes:
            - /applications/tatulli:/config
        ports:
            - 8181:8181/tcp
    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
