version: '2.1'
services:
    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /share/applications/nzbget:/config
            - /share/downloads:/downloads
        restart: always
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=100
        ports:
            - 6789:6789/tcp
    sonarr:
        image: linuxserver/sonarr:latest
        container_name: sonarr
        depends_on:
            - nzbget
        volumes:
            - /share/applications/sonarr:/config
            - /share/downloads:/downloads
            - /share/media/tv:/tv
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=100
        ports:
            - 8989:8989/tcp
    radarr:
        image: linuxserver/radarr:latest
        container_name: radarr
        depends_on:
            - nzbget
        volumes:
            - /share/applications/radarr:/config
            - /share/downloads:/downloads
            - /share/media/movies:/movies
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=100
        ports:
            - 7878:7878/tcp
    tatulli:
        image: linuxserver/tautulli
        container_name: plexreports
        volumes:
            - /share/applications/tatulli:/config
        ports:
            - 8181:8181/tcp
        environment:
            - PUID=1000
            - PGID=100
    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
